[package]
name = "libicsneo-rs"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/intrepidcs/libicsneo-rs"
authors = ["David Rebbe <drebbe@intrepidcs.com>"]
readme = "readme.md"
description = "Rust API for libicsneo"
keywords = ["libicsneo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libicsneo-sys = "0.1.3"

[features]
default = ["test_zero_devices"]
test_zero_devices = []